### PR TITLE
fix(yaml): fix $import for arrays

### LINKED ISSUE #310: Yaml $import operation not working at array elements
# Problem

Load file `loaded.yaml` with $import

**source:** 

```yaml
# loaded.yaml
array:
  - configuration:
       $import: './b.yaml'
```

```yaml
# b.yaml
b: 1
```

**result**
```json
{
    "array": [{ "configuration": { "$import": "./b.yaml" } }]
}
```

**expect**
```json
{
    "array": [{ "configuration": { "b": 1 } }]
}
```

### PR DESCRIPTION
**Pull request by burlakilia**
Close #310

### CODE REVIEW

File: libraries/yaml/source/extensions/$import.js [hunk 1]
```diff
@@ -8,6 +8,10 @@ const { file } = require('@toa.io/filesystem')
 const $import = (object, path, yaml) => {
   return traverse(object, (node) => {
     if ('$import' in node) extend(node, path, yaml)
+
+    for (const [, value] of Object.entries(node)) {
```
Comment (temich) [inline libraries/yaml/source/extensions/$import.js:12]: `Object.values()`

File: libraries/yaml/test/import.test.js [hunk 2]
```diff
@@ -64,3 +64,16 @@ it('should throw exception if file not found', async () => {
 
   await expect(load(path)).rejects.toThrow('No files matching pattern')
 })
+
+it('should import in array element', async () => {
```
Comment (temich) [inline libraries/yaml/test/import.test.js:68]: *into array elements*

**Review by temich — CHANGES_REQUESTED** [review]

File: libraries/yaml/test/examples/imports/arrays/a.yaml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+array:
```
Comment (temich) [inline libraries/yaml/test/examples/imports/arrays/a.yaml:1]: Please add more tests:

```yaml
- $import: ...
```

```yaml
array:
  - 'hello'
  - $import: ...
  - null
```

**Review by temich — APPROVED** [review]
